# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r_github_packages: 
  - jdreyf/ezlimma
  - r-lib/vdiffr
bioc_packages: limma
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
after_success:
  - Rscript -e 'covr::codecov()'