# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r_github_packages: 
  - jdreyf/ezlimma
# https://www.tidyverse.org/articles/2019/01/vdiffr-0-3-0/
env:
  - VDIFFR_RUN_TESTS=false
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
after_success:
  - Rscript -e 'covr::codecov()'